name: Build and Publish Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      # If you want to ensure your build is correct before building Docker,
      # you can do it directly in CI. (This step is optional because the Dockerfile
      # also does the build in the "builder" stage.)
      - name: Build Angular
        run: npm run build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          # Point to the Dockerfile in the root directory
          context: .
          file: ./Dockerfile
          push: true
          tags: chrptvn/minutemail-web:1.0.0

      - name: Log out of Docker Hub
        run: docker logout
